# Generated by Django 4.2.15 on 2025-07-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, unique=True)),
                ('dsc', models.TextField(max_length=425)),
                ('price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('image', models.ImageField(upload_to='catalog_images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('dsc', models.TextField(blank=True, max_length=456, null=True)),
            ],
        ),
    ]
